(feat): support for multiple type params in tax query used in api res…
OpenWebconcept/plugin-openpub-base pull request #19
Opened 2023-09-27 12:45 UTC by mvdhoek1

…ponses

2023-10-13 06:53 UTC, YvetteNikolov approved these changes

2023-10-16 09:03 UTC, robertbossaert approved these changes

2023-10-17 09:01 UTC, sanderdekroon requested changes

2023-10-23 07:32 UTC, mvdhoek1 commented on src/Base/Repositories/Item.php
> +    public static function addTypeParameters(string $types): array
Geen probleem, je hebt gelijk. Ik heb het aangepast. Daarnaast heb ik de openpub-internal-data ook aangepast in deze [PR](https://github.com/OpenWebconcept/plugin-openpub-internal-data/pull/5)

2023-10-23 11:34 UTC, sanderdekroon approved these changes
🙌

2023-10-26 16:13 UTC, merged

2023-10-26 16:16 UTC, mvdhoek1 commented on src/Base/RestAPI/Controllers/ItemController.php
> +            $typeParams = implode(',', $typeParams); // Implode to string because of backward compatibility.
Omdat je vanuit de url ook een array mee kunt geven:
![Scherm­afbeelding 2023-10-26 om 18 15 09](https://github.com/OpenWebconcept/plugin-openpub-base/assets/11852816/a35cd8b5-2104-461f-b8f0-1fe42186df2b)

Deze imploden we dan naar een comma seperated string. Die dan weer als array gebruikt kan worden in:
```
    public static function addTypeParameters(string $types): array
    {
        $types = explode(',', $types); // Explode to array for usage inside the query.

        return [
            'tax_query' => [
                [
                    'taxonomy' => 'openpub-type',
                    'terms'    => array_map(function ($type) {
                        return sanitize_text_field($type);
                    }, $types),
                    'field'    => 'slug',
                    'operator' => 'IN'
                ]
            ]
        ];
    }
```